helmDefaults:
  wait: true
  atomic: false
  timeout: 600

repositories:
  - name: cilium
    url: https://helm.cilium.io/

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  local-bpf: {}
  local-kube-proxy: {}

releases:
  - name: cilium
    chart: cilium/cilium
    version: 1.11.10
    namespace: cilium-system
    values:
    {{- if eq .Environment.Name "local-bpf" }}
      - cilium/values-local-bpf.yaml
    {{- end }}
    {{ if eq .Environment.Name "local-kube-proxy" }}
      - cilium/values-local-kubeproxy.yaml
    {{- end }}
      - cilium/values-local-common.yaml

  - name: nginx
    installed: true
    chart: ingress-nginx/ingress-nginx
    version: 4.0.19
    namespace: nginx
    values:
      - nginx/values-local.yaml

  - name: ext-auth
    chart: ./auth/base
    
